version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    #`volumes:
      #- ./data:/opt/zookeeper-3.4.9/data
    ports:
      - "2181:2181"
    restart: always
  kafka:
#    image: wurstmeister/kafka
    image: ccr.ccs.tencentyun.com/cbbing/kafka:0.10.2.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.4
      KAFKA_MESSAGE_MAX_BYTES: 2000000 # kafka 会接收单个消息size的最大限制
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1  #2副本
      KAFKA_NUM_PARTITIONS: 2
      KAFKA_LOG_RETENTION_BYTES: 1073741824  #超过1G大小后删除
      KAFKA_LOG_RETENTION_HOURS: 72  #日志片段保留3天，默认为7天
    volumes:
      #- ./kafka-logs:/kafka
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9021:9000
    environment:
      ZK_HOSTS: zookeeper:2181
    restart: always